In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.multioutput import MultiOutputClassifier, MultiOutputRegressor

# classification
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

# regression
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestRegressor

# Загружаем данные

In [27]:
import xgboost as xgb

clf = xgb.XGBClassifier()
clf.fit()

TypeError: fit() missing 2 required positional arguments: 'X' and 'y'

In [30]:
import catboost as cb

clf = cb.CatBoostClassifier()
clf.fit()

TypeError: fit() missing 1 required positional argument: 'X'

In [2]:
def split_data_to_X_y(df, y_cols):
    X = df.drop(y_cols, axis=1)
    y = df[y_cols]
    return X, y

## train

In [3]:
df_train = pd.read_csv('data/Nti2018_task2Train.csv', index_col='index')

# удаляем ненужные колонки
cols_to_drop = ['brs_id']
df_train = df_train.drop(cols_to_drop, axis=1)

# находим колонки которые нужно предсказывать
y_cols = df_train.columns[df_train.columns.str.contains('Avg')]

# удаляем дубликаты
# df_train.drop_duplicates(inplace=True)

print(df_train.shape)
df_train.head()

(4720, 69)

,Направление,Основа,Формирующее подразделение (институт),Формирующее подразделение (департамент),Курс,Год начала,Срок освоения,Средняя оценка,Средняя оценка по первой сдаче,Код,...,ИЗ Avg,ИТ Avg,КЗ Avg,ПЗ Avg,Практ Avg,РТ Avg,Т Avg,ТЗ Avg,Тест Avg,УЗ Avg
index,,,,,,,,,,,,,,,,,,,,,
4031,uncass18ggl5g0000j12bmf3eofkej3s,сверхплановое место,"Физической культуры, спорта и молодежной политики",0,5,2013,5.0,0.00,0.00,43.00.00,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
3880,uncass18ggl5g0000kail4d1g44ti8bs,сверхплановое место,Строительный,0,3,2015,4.0,60.49,57.65,08.00.00,...,0.986207,0.0,0.0,0.666667,0.956915,0.0,0.0,0.0,0.0,0.0
5292,uncass18ggl5g0000kaou92csl390qkc,госбюджетное место,Радиоэлектроники и информационных технологий -...,Школа профессионального и академического образ...,2,2016,5.5,56.10,56.10,11.00.00,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
1028,uncass18ggl5g0000kail4d1g44ti8bs,сверхплановое место,Строительный,0,2,2016,3.6,0.00,0.00,08.00.00,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
2508,uncass18ggl5g0000kail4d1g44ti8bs,госбюджетное место,Строительный,0,3,2015,4.0,70.34,69.71,08.00.00,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0

In [4]:
data_train, y_train = split_data_to_X_y(df_train, y_cols)
print(data_train.shape, y_train.shape)

(4720, 43) (4720, 26)

In [48]:
data_train.loc[3880]

Направление                                uncass18ggl5g0000kail4d1g44ti8bs
Основа                                                  сверхплановое место
Формирующее подразделение (институт)                           Строительный
Формирующее подразделение (департамент)                                   0
Курс                                                                      3
Год начала                                                             2015
Срок освоения                                                             4
Средняя оценка                                                        60.49
Средняя оценка по первой сдаче                                        57.65
Код                                                                08.00.00
ОКСО                                                               08.03.01
Направление.1                                                 Строительство
Уровеь                                                                   62
Уровень                                                            Бакалавр
Форма                                                                 Очная
Олимпиада                                                                 0
Физическая культура                                                       0
Рисунок                                                                   0
Химия                                                                     0
География                                                                 0
Информатика и ИКТ                                                         0
История                                                                   0
Математика                                                               55
Композиционный рисунок                                                    0
Композиция                                                                0
Рисунок и композиция                                                      0
Русский язык                                                             87
Творческий конкурс                                                        0
Собеседование                                                             0
Филология (отечественная)                                                 0
Творческое сочинение                                                      0
Литература                                                                0
Филология                                                                 0
Биология                                                                  0
Физика                                                                   58
Академический рисунок                                                     0
Обществознание                                                            0
Английский язык                                                           0
Вступительный экзамен по программе                                        0
Иностранный язык                                                          0
История искусств                                                          0
id                                                                   190079
username                                                    Denis_Martynkov
Name: 3880, dtype: object

In [50]:
data_train['Олимпиада'].value_counts()

0     4687
ВО      29
О        4
Name: Олимпиада, dtype: int64

In [47]:
qwe = data_train[(data_train['Средняя оценка по первой сдаче'] == 0)]
print(qwe.shape)

(qwe[ege_cols] == 0).all(axis=1).sum()

(2274, 43)

645

In [33]:
(data_train['Средняя оценка по первой сдаче'] == 0).sum()

2274

In [41]:
(data_train[ege_cols] == 0).all(axis=1).sum()

1404

In [37]:
(y_train.sum(axis=1) == 0).sum()

2024

In [38]:
(data_test['Средняя оценка по первой сдаче'] == 0).sum()

581

In [42]:
(data_test[ege_cols] == 0).all(axis=1).sum()

344

## 2

In [59]:
col = 'УЗ Avg'
y_train.columns
# y_train_bin[col]
data_train.groupby(y_train_bin[col])[ege_cols].mean()

,Физическая культура,Рисунок,Химия,География,Информатика и ИКТ,История,Математика,Композиционный рисунок,Композиция,Рисунок и композиция,...,Литература,Филология,Биология,Физика,Академический рисунок,Обществознание,Английский язык,Вступительный экзамен по программе,Иностранный язык,История искусств
УЗ Avg,,,,,,,,,,,,,,,,,,,,,
False,0.226871,0.063691,1.619014,0.097164,2.102510,3.625291,36.705253,0.089028,0.01046,0.0,...,0.797768,0.168294,0.909344,26.88331,0.045328,6.260112,0.046490,0.0,1.638308,0.196188
True,0.509569,0.332536,2.413876,0.377990,2.433014,9.253589,31.698565,0.693780,0.00000,0.0,...,2.712919,0.179426,1.055024,16.76555,0.000000,12.325359,0.239234,0.0,6.619617,0.334928

In [69]:
col_name = 'Математика'
col = data_train[col_name] != 0
y_train.groupby(col).apply(lambda x: (x != 0).sum())#.sum()

,Final Avg,Final Exam Avg,HW Avg,TC Avg,ig Avg,metrology Avg,ng Avg,sootv Avg,stand Avg,termodin Avg,...,ИЗ Avg,ИТ Avg,КЗ Avg,ПЗ Avg,Практ Avg,РТ Avg,Т Avg,ТЗ Avg,Тест Avg,УЗ Avg
Математика,,,,,,,,,,,,,,,,,,,,,
False,51,74,28,31,1,59,9,47,49,7,...,59,89,76,41,60,1,225,186,86,199
True,192,101,27,69,35,196,58,174,184,8,...,212,289,63,208,182,3,569,173,139,219

In [70]:
col = data_train['Курс']
y_train.groupby(col).apply(lambda x: (x != 0).sum())#.sum()

,Final Avg,Final Exam Avg,HW Avg,TC Avg,ig Avg,metrology Avg,ng Avg,sootv Avg,stand Avg,termodin Avg,...,ИЗ Avg,ИТ Avg,КЗ Avg,ПЗ Avg,Практ Avg,РТ Avg,Т Avg,ТЗ Avg,Тест Avg,УЗ Avg
Курс,,,,,,,,,,,,,,,,,,,,,
1,17,7,10,7,1,22,2,20,21,5,...,13,21,23,12,11,1,12,69,39,73
2,37,49,19,8,31,24,57,12,14,4,...,34,38,41,25,69,2,373,114,43,111
3,112,57,11,79,4,144,7,130,137,3,...,163,298,18,191,149,1,391,66,98,69
4,72,62,14,5,0,60,1,54,56,3,...,60,18,56,19,7,0,14,100,41,155
5,5,0,1,1,0,5,0,5,5,0,...,1,3,1,1,6,0,4,10,3,9
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,1

## test

In [5]:
data_test = pd.read_csv('data/xTestFinal_2.csv', index_col='index')
print(data_test.shape)
data_test.head()

(1180, 43)

,Направление,Основа,Формирующее подразделение (институт),Формирующее подразделение (департамент),Курс,Год начала,Срок освоения,Средняя оценка,Средняя оценка по первой сдаче,Код,...,Биология,Физика,Академический рисунок,Обществознание,Английский язык,Вступительный экзамен по программе,Иностранный язык,История искусств,id,username
index,,,,,,,,,,,,,,,,,,,,,
0,uncass18hc2jg0000l6udkbc8999b154,госбюджетное место,Естественных наук и математики,Школа наук,1,2017,2.0,0.00,0.00,04.00.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,298459,egormat97
1,uncass18ggl5g0000kain7dt2j01t94k,госбюджетное место,Новых материалов и технологий,Машиностроения,3,2015,5.0,0.00,0.00,15.00.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,160700,pirojok_rojok
2,uncass18ggl5g0000kaqsplbivu3ie48,сверхплановое место,Государственного управления и предпринимательства,Государственного и муниципального управления,1,2017,5.0,0.00,0.00,38.00.00,...,0.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,200655,mvlysenko
3,uncass18ggl5g0000kainfe9qstfrflk,госбюджетное место,Новых материалов и технологий,Машиностроения,2,2016,4.0,61.26,60.57,23.00.00,...,0.0,65.0,0.0,0.0,0.0,0.0,0.0,0.0,280247,petr_kozlov
4,uncass18hc2jg0000l7f8qta25odb73g,госбюджетное место,Химико-технологический,0,1,2017,2.0,0.00,0.00,18.00.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,146479,SiD28ru

# Генерируем признаки

In [6]:
# объединим train и test в один датафрейм
train_size = len(data_train)
print(train_size)

data = pd.concat([data_train, data_test])
print(data.shape)

4720
(5900, 43)

## Категориальные

In [7]:
cat_cols = [
    'Направление',
    'Основа',
    'Формирующее подразделение (институт)',
    'Формирующее подразделение (департамент)',
    'Курс',
    'Год начала',
    'Код',
    'ОКСО',
    'Направление.1',
    'Уровень',
    'Форма',
    'Олимпиада',
]

In [8]:
def get_cat_features(data, cat_cols):
    return pd.get_dummies(data[cat_cols], columns=cat_cols, drop_first=False)

X_train_cat = get_cat_features(data_train, cat_cols)
print(X_train_cat.shape)

X_test_cat = get_cat_features(data_test, cat_cols)
print(X_test_cat.shape)

(4720, 854)
(1180, 629)

Видно, что количество признаков для train и test разное. Это логично, т.к. в train данных в 4 раза больше, соответственно там больше различных категорий для некоторых признаков. Нам нужно, чтобы количество признаков было одинаковое!

In [9]:
def prepare_str_col(col):
    if col.dtype != object:
        return col
    return col.str.lower().str.replace(' +', ' ').str.strip()

In [10]:
data = data.apply(prepare_str_col)
X_cat = get_cat_features(data, cat_cols)
print(X_cat.shape)

(5900, 885)

# Count Encoder

для каждого категориального признака заменяем значение на частоту встречаемости категории

пример
категориальный признак:
[a, b, c, a, a, b]
он же, закодированный с помощью count encoding:
[3, 2, 1, 3, 3, 2]

In [11]:
def count_ecoder(col):
    counts = col.value_counts()
    return col.map(counts)

X_count = data[cat_cols].apply(count_ecoder)
print(X_count.shape)

(5900, 12)

## Числовые признаки - оценки за ЕГЭ и сроки

In [12]:
ege_cols = [
    'Физическая культура',
    'Рисунок',
    'Химия',
    'География',
    'Информатика и ИКТ',
    'История',
    'Математика',
    'Композиционный рисунок',
    'Композиция',
    'Рисунок и композиция',
    'Русский язык',
    'Творческий конкурс',
    'Собеседование',
    'Филология (отечественная)',
    'Творческое сочинение',
    'Литература',
    'Филология',
    'Биология',
    'Физика',
    'Академический рисунок',
    'Обществознание',
    'Английский язык',
    'Вступительный экзамен по программе',
    'Иностранный язык',
    'История искусств',
]

numerical_cols = [
    'Курс',
    'Год начала',
    'Срок освоения',
    'Средняя оценка ',
    'Средняя оценка по первой сдаче',
]

X_cont = data[ege_cols + numerical_cols]
print(X_cont.shape)
X_cont.head()

(5900, 30)

,Физическая культура,Рисунок,Химия,География,Информатика и ИКТ,История,Математика,Композиционный рисунок,Композиция,Рисунок и композиция,...,Обществознание,Английский язык,Вступительный экзамен по программе,Иностранный язык,История искусств,Курс,Год начала,Срок освоения,Средняя оценка,Средняя оценка по первой сдаче
index,,,,,,,,,,,,,,,,,,,,,
4031,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5,2013,5.0,0.00,0.00
3880,0.0,0.0,0.0,0.0,0.0,0.0,55.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3,2015,4.0,60.49,57.65
5292,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2,2016,5.5,56.10,56.10
1028,0.0,0.0,0.0,0.0,0.0,0.0,48.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2,2016,3.6,0.00,0.00
2508,0.0,0.0,0.0,0.0,0.0,0.0,70.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3,2015,4.0,70.34,69.71

## Бинарные признаки - сдавал ли ЕГЭ

In [13]:
X_bin = data[ege_cols] != 0
print(X_bin.shape)
X_bin.head()

(5900, 25)

,Физическая культура,Рисунок,Химия,География,Информатика и ИКТ,История,Математика,Композиционный рисунок,Композиция,Рисунок и композиция,...,Литература,Филология,Биология,Физика,Академический рисунок,Обществознание,Английский язык,Вступительный экзамен по программе,Иностранный язык,История искусств
index,,,,,,,,,,,,,,,,,,,,,
4031,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3880,False,False,False,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
5292,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1028,False,False,False,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2508,False,False,False,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False

## Объединяем все признаки

In [14]:
X = pd.concat([X_cat, X_count, X_cont, X_bin], axis=1)
print(X.shape)

# разбиваем обратно на train и test
X_train = X.iloc[:train_size]
X_test = X.iloc[train_size:]
print(X_train.shape, X_test.shape)

(5900, 952)
(4720, 952) (1180, 952)

# Обучаем и оцениваем модель
## Предсказываем, проходил ли курс или нет

In [15]:
def print_score(y_bin, y_bin_pred):
    for col in y_cols:
        print('{}'.format(col))
        top_class_rate = y_train_bin[col].value_counts(normalize=True)[0]
        acc = accuracy_score(y_train_bin[col], y_train_bin_pred[col])
        prec = precision_score(y_train_bin[col], y_train_bin_pred[col])
        rec = recall_score(y_train_bin[col], y_train_bin_pred[col])
        print('\t{:.3} {:.3}'.format(acc, top_class_rate))
        print('\t{:.3} {:.3}'.format(prec, rec))

In [16]:
y_train_bin = y_train != 0
y_train_bin.head()

,Final Avg,Final Exam Avg,HW Avg,TC Avg,ig Avg,metrology Avg,ng Avg,sootv Avg,stand Avg,termodin Avg,...,ИЗ Avg,ИТ Avg,КЗ Avg,ПЗ Avg,Практ Avg,РТ Avg,Т Avg,ТЗ Avg,Тест Avg,УЗ Avg
index,,,,,,,,,,,,,,,,,,,,,
4031,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3880,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,True,False,False,False,False,False
5292,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1028,True,False,False,False,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2508,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [18]:
X_train_prob = pd.DataFrame(index=X_train.index, columns=y_cols)

for col in y_cols:
    model_clf = RandomForestClassifier(n_estimators=1000, n_jobs=-1)
    X_train_prob_col = cross_val_predict(model_clf, \
                                         X_train, \
                                         y_train_bin[col], \
                                         method='predict_proba', \
                                         cv=5)[:, 1]
    X_train_prob[col] = X_train_prob_col

print(X_train_prob.shape)
X_train_prob.head()

/home/Maslovsky/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:597: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)

(4720, 26)

,Final Avg,Final Exam Avg,HW Avg,TC Avg,ig Avg,metrology Avg,ng Avg,sootv Avg,stand Avg,termodin Avg,...,ИЗ Avg,ИТ Avg,КЗ Avg,ПЗ Avg,Практ Avg,РТ Avg,Т Avg,ТЗ Avg,Тест Avg,УЗ Avg
index,,,,,,,,,,,,,,,,,,,,,
4031,0.027500,0.000,0.004225,0.0,0.000000,0.027667,0.00000,0.02725,0.032,0.0,...,0.000000,0.007208,0.0036,0.617000,0.669500,0.0,0.016667,0.046785,0.003733,0.036050
3880,0.000000,0.002,0.000000,0.0,0.000000,0.000000,0.00000,0.00000,0.000,0.0,...,0.072395,0.853049,0.0135,0.083124,0.064796,0.0,0.856683,0.021717,0.042405,0.017517
5292,0.000000,0.000,0.003000,0.0,0.000000,0.000000,0.00000,0.00000,0.000,0.0,...,0.000000,0.001000,0.0020,0.000000,0.025769,0.0,0.004000,0.002000,0.000000,0.201750
1028,0.226424,0.001,0.000000,0.0,0.294976,0.000000,0.52121,0.00000,0.000,0.0,...,0.000000,0.251454,0.0000,0.000000,0.000000,0.0,0.329576,0.000000,0.000500,0.000000
2508,0.000000,0.000,0.000000,0.0,0.000000,0.000000,0.00000,0.00000,0.000,0.0,...,0.479132,0.067686,0.0000,0.507793,0.067433,0.0,0.057439,0.000000,0.478912,0.000000

In [19]:
model_clf = RandomForestClassifier(n_estimators=1000, n_jobs=-1)
mo_model_clf = MultiOutputClassifier(model_clf)
%time mo_model_clf.fit(X_train, y_train_bin)

%time X_test_prob = mo_model_clf.predict_proba(X_test)
X_test_prob = np.vstack(probas[:, 1] for probas in X_test_prob).swapaxes(0, 1)
X_test_prob = pd.DataFrame(X_test_prob, index=X_test.index, columns=y_cols)
print(X_test_prob.shape)
X_test_prob.head()

CPU times: user 6min 2s, sys: 13.9 s, total: 6min 16s
Wall time: 48.7 s
CPU times: user 13.6 s, sys: 1.43 s, total: 15.1 s
Wall time: 10 s
(1180, 26)

,Final Avg,Final Exam Avg,HW Avg,TC Avg,ig Avg,metrology Avg,ng Avg,sootv Avg,stand Avg,termodin Avg,...,ИЗ Avg,ИТ Avg,КЗ Avg,ПЗ Avg,Практ Avg,РТ Avg,Т Avg,ТЗ Avg,Тест Avg,УЗ Avg
index,,,,,,,,,,,,,,,,,,,,,
0,0.002000,0.001000,0.003111,0.007221,0.000000,0.000000,0.000000,0.000000,0.001667,0.006817,...,0.128892,0.006794,0.004450,0.000643,0.001515,0.0,0.000593,0.029675,0.009113,0.097604
1,0.341348,0.302195,0.000000,0.319840,0.000000,0.336028,0.000200,0.337108,0.330002,0.000000,...,0.000000,0.341429,0.000000,0.000000,0.000250,0.0,0.320318,0.006324,0.000111,0.003467
2,0.060497,0.010788,0.042000,0.000000,0.005627,0.004250,0.008694,0.000000,0.000000,0.001400,...,0.005000,0.005536,0.002393,0.000000,0.009148,0.0,0.003483,0.388117,0.002000,0.398167
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000167,0.000000,0.000000,0.000000,...,0.000500,0.001000,0.001000,0.000000,0.000000,0.0,0.330917,0.000000,0.000000,0.000750
4,0.000000,0.000000,0.000583,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.006104,0.002162,0.007740,0.000000

## Предсказываем среднюю оценку за курс

In [21]:
X_train_ = pd.concat([X_train, X_train_prob], axis=1)
X_test_ = pd.concat([X_test, X_test_prob], axis=1)

In [22]:
model = RandomForestRegressor(n_estimators=1000, n_jobs=-1)
mo_model = MultiOutputRegressor(model)
%time mo_model.fit(X_train_, y_train)

y_test_pred = mo_model.predict(X_test_)
y_test_pred = pd.DataFrame(y_test_pred, index=data_test.index, columns=y_cols)
y_test_pred.head()

CPU times: user 3h 16min 44s, sys: 7.7 s, total: 3h 16min 52s
Wall time: 6min 16s

,Final Avg,Final Exam Avg,HW Avg,TC Avg,ig Avg,metrology Avg,ng Avg,sootv Avg,stand Avg,termodin Avg,...,ИЗ Avg,ИТ Avg,КЗ Avg,ПЗ Avg,Практ Avg,РТ Avg,Т Avg,ТЗ Avg,Тест Avg,УЗ Avg
index,,,,,,,,,,,,,,,,,,,,,
0,0.000000,0.000000,9.546932e-09,0.000003,0.000000,0.000000,0.000003,0.000000,0.000000,0.000002,...,0.001124,0.000000,0.000000,0.0,0.000001,0.0,0.000007,0.009007,5.397169e-04,0.114104
1,0.147003,0.003830,9.546932e-09,0.043802,0.004670,0.529856,0.005777,0.450706,0.467077,0.000002,...,0.000000,0.026783,0.000000,0.0,0.000778,0.0,0.080823,0.000001,1.753033e-09,0.000246
2,0.070799,0.012337,2.398462e-02,0.000003,0.001784,0.011901,0.000001,0.000000,0.000000,0.000002,...,0.000000,0.015367,0.066298,0.0,0.003936,0.0,0.014748,0.122276,3.472496e-03,0.116853
3,0.000000,0.000000,9.546932e-09,0.010339,0.000000,0.000000,0.000537,0.000000,0.000000,0.000002,...,0.000000,0.006000,0.000000,0.0,0.001837,0.0,0.479534,0.001111,1.753033e-09,0.000813
4,0.000000,0.000000,3.000010e-03,0.000003,0.000000,0.000000,0.000003,0.000000,0.000000,0.000002,...,0.000000,0.000650,0.000000,0.0,0.002153,0.0,0.003285,0.000097,5.538462e-04,0.000765

In [23]:
y_test_pred.to_csv('res/out_2_1.csv')

In [24]:
model = LinearRegression(n_jobs=-1)
mo_model = MultiOutputRegressor(model)
%time mo_model.fit(X_train_, y_train)

y_test_pred = mo_model.predict(X_test_)
y_test_pred = pd.DataFrame(y_test_pred, index=data_test.index, columns=y_cols)
y_test_pred.head()

CPU times: user 1min 24s, sys: 8.04 s, total: 1min 32s
Wall time: 5.55 s

,Final Avg,Final Exam Avg,HW Avg,TC Avg,ig Avg,metrology Avg,ng Avg,sootv Avg,stand Avg,termodin Avg,...,ИЗ Avg,ИТ Avg,КЗ Avg,ПЗ Avg,Практ Avg,РТ Avg,Т Avg,ТЗ Avg,Тест Avg,УЗ Avg
index,,,,,,,,,,,,,,,,,,,,,
0,-0.001930,0.007258,-0.004346,-0.000081,-0.006922,0.010229,-0.006047,0.010003,0.009260,0.000953,...,0.065885,0.006103,0.011323,0.006914,-0.012695,-0.000596,-0.046918,0.023569,0.017675,0.069163
1,0.134874,0.072148,-0.003686,0.110188,0.003411,0.252042,-0.001348,0.231673,0.223986,-0.000385,...,0.057592,0.183973,0.014096,0.075958,0.092528,-0.000541,0.194278,0.015011,0.018187,-0.023014
2,0.022381,0.002408,0.021060,-0.033014,0.012756,-0.023639,0.004335,-0.021567,-0.029641,0.002063,...,0.009580,-0.036720,0.021873,0.029235,0.018153,0.003704,-0.032959,0.035882,0.037118,0.038282
3,-0.011009,0.006715,-0.001531,0.007030,0.003709,-0.021988,0.005365,-0.020911,-0.017641,-0.000542,...,-0.011857,0.064269,0.013548,-0.012897,0.009949,-0.000111,0.341938,0.015319,-0.017610,0.012279
4,0.012297,-0.000401,0.001859,-0.001386,-0.002683,0.018055,-0.003770,0.018470,0.016349,0.000557,...,-0.011896,-0.012882,0.000549,-0.010118,0.000254,-0.000081,-0.010993,0.001237,0.005556,-0.003488

In [25]:
y_test_pred.to_csv('res/out_2_2.csv')